wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1646574549
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 2
      - 13
      - 24
      - 35
      4: 3.9.7
      5: 0.12.11
      8:
      - 3
      - 5
